// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'Models/users.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 57095473126899600),
      name: 'User',
      lastPropertyId: const IdUid(7, 1607957145537559661),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4387022688211906191),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1603003842089800618),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 9081226762942562278),
            name: 'gamesWonvsComputer',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1582567236435757397),
            name: 'gamesWonvsPlayer',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2795214194151864283),
            name: 'gamesPlayedvsComputer',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 4653382630298753388),
            name: 'gamesPlayedvsPlayer',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 1607957145537559661),
            name: 'consectiveWins',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 57095473126899600),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    User: EntityDefinition<User>(
        model: _entities[0],
        toOneRelations: (User object) => [],
        toManyRelations: (User object) => {},
        getId: (User object) => object.id,
        setId: (User object, int id) {
          object.id = id;
        },
        objectToFB: (User object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.gamesWonvsComputer);
          fbb.addInt64(3, object.gamesWonvsPlayer);
          fbb.addInt64(4, object.gamesPlayedvsComputer);
          fbb.addInt64(5, object.gamesPlayedvsPlayer);
          fbb.addInt64(6, object.consectiveWins);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = User(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              gamesPlayedvsComputer:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
              gamesPlayedvsPlayer:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
              gamesWonvsComputer:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
              gamesWonvsPlayer:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              consectiveWins:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// see [User.id]
  static final id = QueryIntegerProperty<User>(_entities[0].properties[0]);

  /// see [User.name]
  static final name = QueryStringProperty<User>(_entities[0].properties[1]);

  /// see [User.gamesWonvsComputer]
  static final gamesWonvsComputer =
      QueryIntegerProperty<User>(_entities[0].properties[2]);

  /// see [User.gamesWonvsPlayer]
  static final gamesWonvsPlayer =
      QueryIntegerProperty<User>(_entities[0].properties[3]);

  /// see [User.gamesPlayedvsComputer]
  static final gamesPlayedvsComputer =
      QueryIntegerProperty<User>(_entities[0].properties[4]);

  /// see [User.gamesPlayedvsPlayer]
  static final gamesPlayedvsPlayer =
      QueryIntegerProperty<User>(_entities[0].properties[5]);

  /// see [User.consectiveWins]
  static final consectiveWins =
      QueryIntegerProperty<User>(_entities[0].properties[6]);
}
