// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMhiUXCNosfNbcCDmDd2WA1HHkkD98GA4',
    appId: '1:911914400261:web:5ef59afb16b7f8e20c7a6c',
    messagingSenderId: '911914400261',
    projectId: 'shop-corner-c83ba',
    authDomain: 'shop-corner-c83ba.firebaseapp.com',
    storageBucket: 'shop-corner-c83ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ZudlhEcmeKjREpZdnvE7pF6-rIwyhFU',
    appId: '1:911914400261:android:308fc407b1e0ff460c7a6c',
    messagingSenderId: '911914400261',
    projectId: 'shop-corner-c83ba',
    storageBucket: 'shop-corner-c83ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgRCW-JOdfZDEpEQyPL6hDSeMytQ4RbE8',
    appId: '1:911914400261:ios:27b10607887ae4da0c7a6c',
    messagingSenderId: '911914400261',
    projectId: 'shop-corner-c83ba',
    storageBucket: 'shop-corner-c83ba.appspot.com',
    iosClientId: '911914400261-el2itba8l4jum71q99bjdvtk1kaibqom.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopcorner',
  );
}
